// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface MessagePrx extends Ice.ObjectPrx
{
    public void sendOrReceive(String message);

    public void sendOrReceive(String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendOrReceive(String message);

    public Ice.AsyncResult begin_sendOrReceive(String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendOrReceive(String message, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendOrReceive(String message, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendOrReceive(String message, Callback_Message_sendOrReceive __cb);

    public Ice.AsyncResult begin_sendOrReceive(String message, java.util.Map<String, String> __ctx, Callback_Message_sendOrReceive __cb);

    public Ice.AsyncResult begin_sendOrReceive(String message, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendOrReceive(String message, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendOrReceive(String message, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendOrReceive(String message, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendOrReceive(Ice.AsyncResult __result);
}
